[build]
  base = "Frontend"
  publish = "Frontend/dist"
  command = "CI=false pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--package-lock-only=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
